import { colors } from '@mui/material';
import { makeStyles } from 'tss-react/mui';

const COLORS = {
    dark: '#2c3e50',
    darkLight: 'rgba(44,62,80,0.09)',
    darkBorder: 'rgba(44,62,80,0.07)',
    darkBorderMd: 'rgba(44,62,80,0.08)',
    darkBorderSm: 'rgba(44,62,80,0.05)',
    darkOverlay: 'rgba(44,62,80,0.025)',
    darkIcon: 'rgba(44,62,80,0.2)',
    darkDone: 'rgba(120, 120, 120, 0.2)',

    textPrimary: '#161616',
    textSecondary: '#5b5d5e',
    textMuted: '#95a5a6',
    textLight: '#bdc3c7',
    white: '#fff',
    whiteAlpha48: 'rgba(255,255,255,0.48)',
    whiteAlpha42: 'rgba(255,255,255,0.42)',

    dispatchedBg: 'rgba(41,128,185,0.1)',
    dispatchedColor: '#1a5276',
    dispatchedBorder: 'rgba(41,128,185,0.3)',

    pickedUpBg: 'rgba(221,145,0,0.1)',
    pickedUpColor: '#7d5200',
    pickedUpBorder: 'rgba(221,145,0,0.3)',

    deliveredBg: 'rgba(39,174,96,0.1)',
    deliveredColor: '#1a5e35',
    deliveredBorder: 'rgba(39,174,96,0.3)',

    completedBg: 'rgba(39,174,96,0.15)',
    completedColor: '#1a5e35',
    completedBorder: 'rgba(39,174,96,0.4)',

    green: '#27ae60',
    greenCC: '#27ae60CC',
    greenBg: 'rgba(39,174,96,0.08)',
    greenBgHover: 'rgba(39,174,96,0.16)',
    greenBorder: 'rgba(39,174,96,0.18)',
    greenDone: '#1a5e35',
    greenDoneBg: 'rgba(39,174,96,0.1)',
    greenDoneBorder: 'rgba(39,174,96,0.25)',
    greenShadow: 'rgba(39,174,96,0.4)',

    blue: '#2980b9',
    blueCC: '#2980b9CC',
    blueBg: 'rgba(41,128,185,0.08)',
    blueBgHover: 'rgba(41,128,185,0.16)',
    blueBorder: 'rgba(41,128,185,0.18)',
    blueShadow: 'rgba(41,128,185,0.4)',

    amber: '#DD9100',
    amberBg: 'rgba(221,145,0,0.18)',
    amberBorder: 'rgba(221,145,0,0.45)',

    emptyIconBg: 'rgba(44,62,80,0.08)',
};

export const ORDER_STATUS_STYLES = {
    dispatched: { bg: COLORS.dispatchedBg, color: COLORS.dispatchedColor, border: `1px solid ${COLORS.dispatchedBorder}` },
    'picked up': { bg: COLORS.pickedUpBg, color: COLORS.pickedUpColor, border: `1px solid ${COLORS.pickedUpBorder}` },
    delivered: { bg: COLORS.deliveredBg, color: COLORS.deliveredColor, border: `1px solid ${COLORS.deliveredBorder}` },
    completed: { bg: COLORS.completedBg, color: COLORS.completedColor, border: `1px solid ${COLORS.completedBorder}` },
};

export const useStyles = makeStyles()(() => ({

    notifBtn: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: 32,
        height: 32,
        borderRadius: 8,
        background: 'rgba(227, 200, 197, 0.15)',
        border: '1px solid rgba(223, 198, 195, 0.35)',
        cursor: 'pointer',
        padding: 0,
        transition: 'background 0.15s',
        '&:hover': {
            background: 'rgba(226, 197, 193, 0.25)',
        },
        '&:active': {
            transform: 'scale(0.95)',
        },
    },
    notifIcon: {
        fontSize: 17,
        color: '#fff',
        animation: 'bellShake 1s ease-in-out infinite',
        '@keyframes bellShake': {
            '0%, 100%': { transform: 'rotate(0deg)' },
            '10%': { transform: 'rotate(-18deg)' },
            '20%': { transform: 'rotate(18deg)' },
            '30%': { transform: 'rotate(-12deg)' },
            '40%': { transform: 'rotate(12deg)' },
            '50%': { transform: 'rotate(-6deg)' },
            '60%': { transform: 'rotate(6deg)' },
            '70%': { transform: 'rotate(0deg)' },
        },
    },
    notifDot: {
        position: 'absolute',
        top: 5,
        right: 5,
        width: 7,
        height: 7,
        borderRadius: '50%',
        background: '#fff',
        border: '1.5px solid #2c3e50',
        // animation: 'pulseDot 1.4s ease-in-out infinite',
        // '@keyframes pulseDot': {
        // '0%, 100%': { opacity: 1, transform: 'scale(1)' },
        // '50%': { opacity: 0.4, transform: 'scale(0.7)' },
        // },
    },
    notifCollapse: {
        marginTop: 8,
        marginBottom: 8,
        borderRadius: 10,
        overflow: 'hidden',
    },

    freightHeaderRow: {
        padding: '4px 8px',
        marginBottom: 4,
        background: COLORS.darkLight,
    },
    freightHeaderText: {
        fontWeight: 700,
    },
    freightRow: {
        padding: '6px 8px',
        borderRadius: 4,
        '&:not(:last-child)': {
            borderBottom: `1px solid ${COLORS.darkBorderSm}`,
        },
    },
    freightPieceBadge: {
        width: 20,
        height: 20,
        borderRadius: 5,
        background: COLORS.darkLight,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 13,
        fontWeight: 800,
    },
    freightType: {
        fontSize: 13,
        fontWeight: 700,
        color: COLORS.dark,
    },
    freightDims: {
        fontSize: 13,
        fontWeight: 500,
        color: COLORS.dark,
        fontVariantNumeric: 'tabular-nums',
    },
    freightDesc: {
        fontSize: 13,
        color: COLORS.dark,
    },
    freightTotalsRow: {
        display: 'flex',
        gap: 16,
        marginTop: 8,
        paddingTop: 8,
        justifyContent: 'flex-end',
        borderTop: `1px solid ${COLORS.darkBorderMd}`,
        paddingLeft: 8,
        paddingRight: 8,
        alignItems: 'center',
    },
    freightTotalNumber: {
        fontSize: 15,
        fontWeight: 800,
        color: COLORS.dark,
        fontVariantNumeric: 'tabular-nums',
    },
    freightTotalUnit: {
        fontSize: 11,
        fontWeight: 700,
        color: COLORS.textMuted,
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    freightTotalDot: {
        width: 3,
        height: 3,
        borderRadius: '50%',
        background: COLORS.darkIcon,
        alignSelf: 'center',
    },

    legRow: {
        width: '100%',
        padding: '9.6px 12px',
        cursor: 'pointer',
        transition: 'background 0.15s',
        borderTop: `1px solid ${COLORS.darkBorder}`,
    },
    legRowDone: {
        background: COLORS.darkLight,
    },
    legRowPickupOpen: { background: COLORS.greenBg },
    legRowDeliveryOpen: { background: COLORS.blueBg },
    legRowPickupHover: { '&:hover': { background: COLORS.greenBg } },
    legRowDeliveryHover: { '&:hover': { background: COLORS.blueBg } },

    legCircleDone: {
        background: `${colors.grey['500']} !important`,
        boxShadow: 'none !important',
    },

    legCirclePickup: {
        position: 'relative',
        width: 32,
        height: 32,
        borderRadius: '50%',
        background: `linear-gradient(135deg, ${COLORS.green}, ${COLORS.greenCC})`,
        color: COLORS.white,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 14,
        fontWeight: 800,
        letterSpacing: '0.05em',
        flexShrink: 0,
        boxShadow: `0 4px 10px ${COLORS.greenShadow}`,
    },
    pulseCirclePickup: {
        '&::before': {
            content: '""',
            position: 'absolute',
            inset: -1,
            borderRadius: '50%',
            border: `2px solid ${COLORS.green}`,
            opacity: 0,
            animation: 'pulseRingGreen 2s ease-out infinite',
        },
        '@keyframes pulseRingGreen': {
            '0%': { transform: 'scale(1)', opacity: 0.6 },
            '100%': { transform: 'scale(1.5)', opacity: 0 },
        },
    },

    pulseCircleDelivery: {
        '&::before': {
            content: '""',
            position: 'absolute',
            inset: -1,
            borderRadius: '50%',
            border: `2px solid ${COLORS.blue}`,
            opacity: 0,
            animation: 'pulseRingBlue 2s ease-out infinite',
        },
        '@keyframes pulseRingBlue': {
            '0%': { transform: 'scale(1)', opacity: 0.6 },
            '100%': { transform: 'scale(1.5)', opacity: 0 },
        },
    },
    legCircleDelivery: {
        position: 'relative',
        width: 32,
        height: 32,
        borderRadius: '50%',
        background: `linear-gradient(135deg, ${COLORS.blue}, ${COLORS.blueCC})`,
        color: COLORS.white,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 14,
        fontWeight: 800,
        letterSpacing: '0.05em',
        flexShrink: 0,
        boxShadow: `0 4px 10px ${COLORS.blueShadow}`,
    },

    legName: {
        fontSize: 14,
        fontWeight: 700,
        color: COLORS.textPrimary,
        // whiteSpace: 'nowrap',
        // overflow: 'hidden',
    },
    legNameDone: { opacity: 0.6 },
    legAddress: {
        fontSize: 13,
        color: COLORS.textSecondary,
        marginTop: 2,
        // whiteSpace: 'nowrap',
        // overflow: 'hidden',
        // textOverflow: 'ellipsis',
    },

    doneBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        fontSize: 16,
        fontWeight: 800,
        color: COLORS.greenDone,
        background: COLORS.greenDoneBg,
        border: `1px solid ${COLORS.greenDoneBorder}`,
        borderRadius: '5px',
        padding: '2.4px 6px',
        letterSpacing: '0.06em',
    },

    actionBtnPickup: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 4,
        padding: '3.2px 8px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: 18,
        fontWeight: 700,
        letterSpacing: '0.04em',
        border: `1px solid ${COLORS.greenBorder}`,
        background: COLORS.greenBg,
        color: COLORS.green,
        transition: 'background 0.15s',
        '&:hover': { background: COLORS.greenBgHover },
        '&:active': { transform: 'scale(0.97)' },
    },
    actionBtnDelivery: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 4,
        padding: '3.2px 8px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: 18,
        fontWeight: 700,
        letterSpacing: '0.04em',
        border: `1px solid ${COLORS.blueBorder}`,
        background: COLORS.blueBg,
        color: COLORS.blue,
        transition: 'background 0.15s',
        '&:hover': { background: COLORS.blueBgHover },
        '&:active': { transform: 'scale(0.97)' },
    },

    expandIcon: {
        fontSize: 25,
        color: COLORS.textMuted,
        transition: 'transform 0.25s',
    },
    expandIconOpen: { transform: 'rotate(180deg)' },
    expandIconClosed: { transform: 'rotate(0)' },

    legDetailLabel: {
        fontSize: 12,
        fontWeight: 700,
        color: COLORS.textMuted,
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        marginBottom: 3.2,
    },
    legDetailValue: {
        fontSize: 14,
        fontWeight: 600,
        color: COLORS.dark,
    },
    legDetailInstructions: {
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 1.5,
    },
    legDetailInstructionsText: { color: COLORS.dark },
    legDetailInstructionsEmpty: { color: COLORS.textLight },

    orderCard: {
        background: COLORS.white,
        border: `1px solid #9f9e9e`,
        borderRadius: 12,
        overflow: 'hidden',
    },
    orderCardHeader: {
        // display: 'flex',
        // alignItems: 'center',
        // gap: 8,
        padding: '8px 12px',
        background: COLORS.darkOverlay,
        borderBottom: `1px solid ${COLORS.darkBorder}`,
    },
    orderIndexBadge: {
        width: 22,
        height: 22,
        borderRadius: 6,
        background: COLORS.dark,
        color: COLORS.white,
        fontSize: 10,
        fontWeight: 800,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    orderNumber: {
        fontSize: 15,
        fontWeight: 800,
        color: COLORS.dark,
        lineHeight: 1.2,
        whiteSpace: 'nowrap',
    },
    orderDateRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        marginTop: 2.4,
    },
    orderDateIcon: {
        fontSize: 12,
        color: COLORS.textMuted,
    },
    orderDate: {
        fontSize: 12,
        color: COLORS.textMuted,
        fontWeight: 500,
    },
    orderCustomerRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
    },
    orderCustomerIcon: {
        fontSize: 12,
        color: COLORS.textMuted,
    },
    orderCustomer: {
        fontSize: 14,
        fontWeight: 600,
        color: COLORS.dark,
    },
    orderRefRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        marginTop: 2.4,
    },
    orderRefIcon: {
        fontSize: 12,
        color: COLORS.textMuted,
    },
    orderRef: {
        fontSize: 12,
        color: COLORS.textMuted,
        fontWeight: 500,
    },
    orderStatusBadge: {
        fontSize: 13,
        fontWeight: 800,
        letterSpacing: '0.07em',
        borderRadius: 5,
        padding: '2.4px 8px',
        textTransform: 'capitalize',
        whiteSpace: 'nowrap',
    },

    tripHeader: {
        background: COLORS.dark,
        borderRadius: 14,
        padding: '12px 16px',
        marginBottom: 16,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    tripIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 10,
        background: COLORS.amberBg,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    tripIcon: {
        fontSize: 22,
        color: COLORS.amber,
    },
    tripNumber: {
        fontFamily: 'Inter, sans-serif',
        fontSize: 16,
        fontWeight: 800,
        color: COLORS.white,
        lineHeight: 1,
    },
    tripDate: {
        fontSize: 13,
        fontWeight: 500,
        color: COLORS.whiteAlpha48,
        marginTop: 3.2,
    },
    liveBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: 4.8,
        background: COLORS.amberBg,
        border: `1px solid ${COLORS.amberBorder}`,
        borderRadius: 6,
        padding: '3.2px 8px',
        fontSize: 13,
        fontWeight: 800,
        color: COLORS.amber,
        letterSpacing: '0.08em',
    },
    liveDot: {
        width: 7,
        height: 7,
        borderRadius: '50%',
        background: COLORS.amber,
        animation: 'blink 1.2s ease-in-out infinite',
        '@keyframes blink': {
            '0%, 100%': { opacity: 1 },
            '50%': { opacity: 0.2 },
        },
    },

    tripProgress: {
        fontSize: 13,
        color: COLORS.whiteAlpha42,
        fontWeight: 600,
    },

    emptyWrap: {
        height: '60vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyInner: {
        textAlign: 'center',
        maxWidth: 320,
        padding: '0 16px',
    },
    emptyIconWrap: {
        width: 70,
        height: 70,
        borderRadius: '50%',
        background: COLORS.emptyIconBg,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '0 auto 12px',
    },
    emptyIcon: {
        fontSize: 32,
        color: COLORS.dark,
        opacity: 0.6,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: 800,
        color: COLORS.dark,
        marginBottom: 4,
    },
    emptySubtitle: {
        fontSize: 13,
        color: COLORS.textMuted,
        lineHeight: 1.5,
    },
}));