import { makeStyles } from 'tss-react/mui'
import { alpha } from '@mui/material'


export const useSectionHeaderStyles = makeStyles()((theme) => ({
    root: {
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1.5),
        px: theme.spacing(2),
        padding: `${theme.spacing(1.5)} ${theme.spacing(2)}`,
        background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.08)} 0%, ${alpha(theme.palette.primary.main, 0.04)} 100%)`,
        borderBottom: `1px solid ${alpha(theme.palette.primary.main, 0.1)}`,
        cursor: 'pointer',
    },
    rootExpanded: {
        borderRadius: '12px 12px 0 0',
    },
    rootCollapsed: {
        borderRadius: '12px',
    },
    accent: {
        width: 4,
        height: 32,
        borderRadius: 4,
        background: theme.palette.primary.main,
        flexShrink: 0,
    },
    editInput: {
        flex: 1,
        '& .MuiOutlinedInput-root': {
            height: 40,
            borderRadius: 2,
            fontSize: 16,
            fontWeight: 700,
        },
    },
    confirmBtn: {
        color: theme.palette.primary.main,
    },
    cancelBtn: {
        '&:hover': { color: '#EF4444' },
    },
    titleRow: {
        flex: 1,
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1.5),
    },
    title: {
        fontSize: 16,
        fontWeight: 700,
        color: '#1E293B',
        letterSpacing: 0.3,
    },
    chip: {
        height: 20,
        fontSize: 13,
        fontWeight: 600,
        background: alpha(theme.palette.primary.main, 0.12),
        color: theme.palette.primary.main,
        '& .MuiChip-label': { px: 1 },
    },
    actions: {
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(2.5),
    },
    editBtn: {
        width: 32,
        height: 32,
        borderRadius: 7,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.1) },
    },
    deleteBtn: {
        width: 32,
        height: 32,
        borderRadius: 7,
        '&:hover': { background: alpha('#EF4444', 0.1), color: '#EF4444' },
    },
    toggleBtn: {
        width: 32,
        height: 32,
        borderRadius: 7,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.08) },
    },
    editIcon: { fontSize: 20, color: '#64748B' },
    deleteIcon: { fontSize: 20, },
    toggleIcon: { fontSize: 20, color: '#94A3B8' },
}))

export const useQuestionRowStyles = makeStyles()((theme) => ({
    root: {
        padding: `${theme.spacing(1.5)} ${theme.spacing(2)}`,
        borderBottom: `1px solid ${alpha(theme.palette.primary.main, 0.06)}`,
        '&:last-child': { borderBottom: 'none' },
        transition: 'background 0.15s',
        '&:hover': { background: alpha(theme.palette.primary.main, 0.015) },
        '&:hover $actions': { opacity: 1 },
    },
    indexBadge: {
        width: 28,
        height: 28,
        borderRadius: 6,
        background: alpha(theme.palette.primary.main, 0.08),
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: theme.spacing(0.3),
    },
    indexText: {
        fontSize: 14,
        fontWeight: 700,
        color: theme.palette.primary.main,
    },
    saveBtn: {
        background: alpha(theme.palette.primary.main, 0.1),
        color: theme.palette.primary.main,
        borderRadius: 7,
        width: 32,
        height: 32,
    },
    cancelBtn: {
        borderRadius: 7,
        width: 32,
        height: 32,
        '&:hover': { color: '#EF4444' },
    },
    labelEN: {
        fontSize: 13,
        fontWeight: 700,
        color: theme.palette.primary.main,
        marginTop: theme.spacing(0.2),
        flexShrink: 0,
    },
    labelFR: {
        fontSize: 13,
        fontWeight: 700,
        color: '#146ce7',
        marginTop: theme.spacing(0.2),
        flexShrink: 0,
    },
    textEN: {
        fontSize: 15,
        fontWeight: 500,
        color: '#1E293B',
        lineHeight: 1.5,
    },
    textFR: {
        fontSize: 15,
        color: '#64748B',
        lineHeight: 1.5,
    },
    gateChip: {
        height: 22,
        fontSize: 9,
        fontWeight: 700,
        background: alpha('#F59E0B', 0.15),
        color: '#D97706',
        '& .MuiChip-label': { paddingLeft: 0.8 * 8, paddingRight: 0.8 * 8 },
    },
    frRow: {
        marginTop: theme.spacing(0.4),
    },
    enRow: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: theme.spacing(1),
        flexWrap: 'wrap',
    },
    actions: {
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1.5),
        opacity: 1,
        transition: 'opacity 0.15s',
    },
    actionBtn: {
        width: 32,
        height: 32,
        borderRadius: 6,
    },
    editBtn: {
        width: 32,
        height: 32,
        borderRadius: 6,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.08) },
    },
    activateBtn: {
        width: 32,
        height: 32,
        borderRadius: 6,
        '&:hover': { background: alpha('#F59E0B', 0.1) },
    },
    deleteBtn: {
        width: 32,
        height: 32,
        borderRadius: 6,
        '&:hover': { background: alpha('#EF4444', 0.1), color: '#EF4444' },
    },
    editIcon: { fontSize: 20, color: '#64748B' },
    editTextField: {
        '& .MuiOutlinedInput-root': { borderRadius: 2, height: 40, fontSize: 15 },
    },
}))


export const useAddQuestionRowStyles = makeStyles()((theme) => ({
    trigger: {
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1),
        padding: `${theme.spacing(1.2)} ${theme.spacing(2)}`,
        cursor: 'pointer',
        borderTop: `1px dashed ${alpha(theme.palette.primary.main, 0.15)}`,
        color: alpha(theme.palette.primary.main, 0.6),
        transition: 'all 0.15s',
        '&:hover': {
            background: alpha(theme.palette.primary.main, 0.03),
            color: theme.palette.primary.main,
        },
        borderRadius: '0 0 12px 12px',
    },
    triggerLabel: { fontSize: 15, fontWeight: 600 },
    form: {
        padding: `${theme.spacing(1.5)} ${theme.spacing(2)}`,
        borderTop: `1px solid ${alpha(theme.palette.primary.main, 0.08)}`,
        background: alpha(theme.palette.primary.main, 0.02),
        borderRadius: '0 0 12px 12px',
    },
    textField: {
        '& .MuiOutlinedInput-root': { borderRadius: 2, fontSize: 15, height: 42 },
    },
    gateLabel: { fontSize: 16, fontWeight: 700, color: '#64748B' },
    checkbox: {
        color: alpha(theme.palette.primary.main, 0.4),
        '&.Mui-checked': { color: theme.palette.primary.main },
    },
    confirmBtn: {
        background: alpha(theme.palette.primary.main, 0.1),
        color: theme.palette.primary.main,
        borderRadius: 7,
        width: 32,
        height: 32,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.2) },
    },
    cancelBtn: {
        borderRadius: 7,
        width: 32,
        height: 32,
        '&:hover': { background: alpha('#EF4444', 0.08), color: '#EF4444' },
    },
}))


export const useQuestionTabStyles = makeStyles()((theme) => ({
    container: { paddingBottom: theme.spacing(4) },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: theme.spacing(3),
        paddingBottom: theme.spacing(2),
        borderBottom: `2px solid ${theme.palette.primary.main}`,
    },
    headerLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1.5),
    },
    headerIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        background: alpha(theme.palette.primary.main, 0.1),
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: { fontSize: 15, fontWeight: 700, color: '#1E293B' },
    headerSubtitle: { fontSize: 13, color: '#94A3B8', fontWeight: 500 },
    addSectionBtn: {
        height: 35,
        borderRadius: 9,
        padding: '0 14px',
        fontSize: 15,
        fontWeight: 600,
        background: alpha(theme.palette.primary.main, 0.1),
        color: theme.palette.primary.main,
        border: `1px solid ${alpha(theme.palette.primary.main, 0.2)}`,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        transition: 'background 0.15s',
    },
    newSectionForm: {
        marginBottom: theme.spacing(2),
        padding: theme.spacing(2),
        borderRadius: 2,
        border: `1.5px dashed ${alpha(theme.palette.primary.main, 0.3)}`,
        background: alpha(theme.palette.primary.main, 0.02),
        display: 'flex',
        gap: theme.spacing(1),
        alignItems: 'center',
    },
    newSectionInput: {
        '& .MuiOutlinedInput-root': { height: 43, borderRadius: 2, fontSize: 13 },
    },
    newSectionConfirm: {
        background: alpha(theme.palette.primary.main, 0.1),
        color: theme.palette.primary.main,
        borderRadius: 7,
        width: 32,
        height: 32,
        flexShrink: 0,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.2) },
    },
    newSectionCancel: {
        borderRadius: 7,
        width: 32,
        height: 32,
        flexShrink: 0,
        '&:hover': { background: alpha('#EF4444', 0.08), color: '#EF4444' },
    },
    emptyState: {
        paddingTop: theme.spacing(8),
        paddingBottom: theme.spacing(8),
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: theme.spacing(1.5),
        border: `1.5px dashed ${alpha(theme.palette.primary.main, 0.15)}`,
        borderRadius: 12,
    },
    emptyIcon: { fontSize: 32, color: '#CBD5E1' },
    emptyTitle: { fontSize: 16, color: '#94A3B8', fontWeight: 600 },
    emptySubtitle: { fontSize: 14, color: '#CBD5E1' },

    sectionCard: {
        border: `1.5px solid #ccc`,
        borderRadius: '12px',
        overflow: 'hidden',
        background: '#fff',
        boxShadow: `0 1px 4px ${alpha(theme.palette.primary.main, 0.06)}`,
        transition: 'box-shadow 0.2s',
        '&:hover': { boxShadow: `0 3px 12px ${alpha(theme.palette.primary.main, 0.1)}` },
    },
    emptySection: {
        padding: `${theme.spacing(2.5)} ${theme.spacing(2)}`,
        display: 'flex',
        alignItems: 'center',
        gap: theme.spacing(1),
    },
    emptySectionText: { fontSize: 14, color: '#CBD5E1', fontStyle: 'italic' },
    loader: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: theme.spacing(10),
        paddingBottom: theme.spacing(10),
    },
}))