import { makeStyles } from 'tss-react/mui';
import { alpha } from '@mui/material';

export default makeStyles()((theme) => ({
    drawerBody: {
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
    },
    scrollArea: {
        flex: 1,
        overflow: 'hidden auto',
        [theme.breakpoints.up('sm')]: {
            padding: '16px 20px',
        }
    },
    listCard: {
        border: `1.5px solid #ccc`,
        borderRadius: 12,
        overflow: 'hidden',
        background: '#fff',
    },
    listHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '13px 14px',
        borderBottom: `1px solid ${alpha(theme.palette.primary.main, 0.08)}`,
        background: alpha(theme.palette.primary.main, 0.03),
        [theme.breakpoints.down('sm')]: {
            padding: '13px 5px',
        }
    },
    listHeaderLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
    },
    listTitle: {
        fontSize: 16,
        fontWeight: 700,
        color: '#1E293B',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    listCount: {
        fontSize: 15,
        fontWeight: 600,
        color: '#94A3B8',
    },
    addBtn: {
        height: 35,
        borderRadius: 8,
        padding: '0 10px',
        fontSize: 16,
        fontWeight: 600,
        textTransform: 'none',
        background: alpha(theme.palette.primary.main, 0.08),
        color: theme.palette.primary.main,
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        transition: 'background 0.15s',
        '&:hover': { background: alpha(theme.palette.primary.main, 0.15) },
    },
    bookRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '12px 14px',
        borderBottom: `1px solid ${alpha(theme.palette.primary.main, 0.06)}`,
        transition: 'background 0.15s',
        '&:last-child': { borderBottom: 'none' },
        '&:hover': { background: alpha(theme.palette.primary.main, 0.02) },
        // '&:hover .bookActions': { opacity: 1 },
    },
    bookIndex: {
        fontSize: 14,
        fontWeight: 700,
        color: '#CBD5E1',
        width: 18,
        flexShrink: 0,
        textAlign: 'center',
    },
    bookName: {
        flex: 1,
        fontSize: 16,
        fontWeight: 600,
        color: '#1E293B',
    },
    bookActions: {
        display: 'flex',
        alignItems: 'center',
        gap: 2,
        // opacity: 0,
        transition: 'opacity 0.15s',
    },
    iconBtn: {
        width: 28,
        height: 28,
        borderRadius: 7,
        padding: 0,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.08) },
    },
    deleteBtn: {
        '&:hover': { background: alpha('#EF4444', 0.08), color: '#EF4444' },
    },
    editInput: {
        flex: 1,
        '& .MuiOutlinedInput-root': { height: 40, borderRadius: 7, fontSize: 18 },
        '& .MuiOutlinedInput-input': { padding: '0 8px', fontSize: 18 },
    },
    confirmBtn: {
        width: 28,
        height: 28,
        borderRadius: 7,
        background: alpha(theme.palette.primary.main, 0.1),
        color: theme.palette.primary.main,
        padding: 0,
        flexShrink: 0,
        '&:hover': { background: alpha(theme.palette.primary.main, 0.2) },
    },
    rowCancelBtn: {
        width: 28,
        height: 28,
        borderRadius: 7,
        padding: 0,
        flexShrink: 0,
        '&:hover': { background: alpha('#EF4444', 0.08), color: '#EF4444' },
    },
    inputRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '8px 14px',
        borderTop: `1px solid ${alpha(theme.palette.primary.main, 0.08)}`,
        background: alpha(theme.palette.primary.main, 0.02),
    },
    input: {
        flex: 1,
        '& .MuiOutlinedInput-root': { height: 40, borderRadius: 8 },
        '& .MuiOutlinedInput-input': { padding: '0 10px', fontSize: 16 },
    },
    emptyState: {
        padding: '24px 14px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: 6,
    },
    emptyText: {
        fontSize: 15,
        color: '#94A3B8',
        fontWeight: 500,
    },
}))