export { default as Login } from './Authentication/Login'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Orders } from './Order/Orders'
export { default as Customers } from './Customers/Customers'
export { default as NewOrder } from './Order/NewOrder'
export { default as RoleView } from './RoleView/Roles'
export { default as Users } from './Users/Users'