import { alpha } from "@mui/material";
import { makeStyles } from "tss-react/mui";

export const useStyles = makeStyles()((theme) => ({
    overlay: {
        position: "fixed",
        inset: 0,
        zIndex: 1400,
        background: alpha(theme.palette.common.black, 0.72),
        backdropFilter: "blur(6px)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: theme.spacing(2),
    },
    card: {
        width: "100%",
        maxWidth: 480,
        borderRadius: theme.shape.borderRadius * 3,
        overflow: "hidden",
    },
    cardHeader: {
        borderBottom: `1px solid ${theme.palette.divider}`,
        padding: theme.spacing(2, 3),
    },
    cardBody: {
        padding: theme.spacing(2.5, 3, 3),
    },
    badge: {
        fontWeight: 800,
        fontSize: 15,
        borderRadius: 99,
        padding: "3px 10px",
        border: `1px solid ${alpha(theme.palette.warning.main, 0.35)}`,
        color: theme.palette.warning.dark,
        background: alpha(theme.palette.warning.main, 0.1),
    },
    sectionPill: {
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: "4px 12px",
        borderRadius: 99,
        background: alpha(theme.palette.warning.main, 0.1),
        border: `1px solid ${alpha(theme.palette.warning.main, 0.28)}`,
        fontSize: 16,
        fontWeight: 700,
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        color: theme.palette.warning.dark,
        marginBottom: theme.spacing(2),
    },
    sectionDot: {
        width: 6,
        height: 6,
        borderRadius: "50%",
        background: theme.palette.warning.main,
        flexShrink: 0,
    },
    questionText: {
        fontSize: 18,
        fontWeight: 700,
        lineHeight: 1.45,
        marginBottom: theme.spacing(1),
    },
    gateWarning: {
        display: "flex",
        alignItems: "center",
        gap: 7,
        marginBottom: theme.spacing(2.5),
        padding: theme.spacing(1, 1.75),
        borderRadius: theme.shape.borderRadius * 1.5,
        background: alpha(theme.palette.warning.main, 0.08),
        border: `1px solid ${alpha(theme.palette.warning.main, 0.22)}`,
        fontSize: 15,
        fontWeight: 600,
        color: theme.palette.warning.dark,
    },
    completionIcon: {
        width: 72,
        height: 72,
        borderRadius: "50%",
        background: alpha(theme.palette.success.main, 0.12),
        border: `2px solid ${alpha(theme.palette.success.main, 0.35)}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
}));