import { makeStyles } from 'tss-react/mui';
import { alpha } from '@mui/material/styles';

export default makeStyles({ name: 'Billing' })((theme) => {

    const isDark = theme.palette.mode === 'dark';
    const primary = theme.palette.primary.main;
    const secondary = theme.palette.secondary.main;
    const shipperColor = theme.palette.success.main;
    const receiverColor = theme.palette.info.main;

    return {
        page: {
            display: 'flex',
            flexDirection: 'column',
            gap: theme.spacing(2),
        },
        toolbarRow: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: theme.spacing(1),
        },
        toolbarButton: {
            height: 32,
            fontSize: 12,
            fontWeight: 700,
            textTransform: 'none',
            borderRadius: 8,
        },
        filterRoot: {
            borderRadius: 16,
            border: '1.5px solid',
            borderColor: isDark ? alpha('#fff', 0.1) : alpha(secondary, 0.14),
            backgroundColor: isDark ? alpha(secondary, 0.25) : alpha(theme.palette.background.default, 0.9),
            overflow: 'hidden',
            boxShadow: isDark ? '0 4px 24px rgba(0,0,0,0.3)' : `0 2px 12px ${alpha(secondary, 0.08)}`,
        },
        filterHeader: {
            padding: theme.spacing(1.25, 2.5),
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer',
            userSelect: 'none',
            transition: 'background 0.15s',
            '&:hover': {
                background: isDark ? alpha('#fff', 0.03) : alpha(primary, 0.04),
            },
        },
        filterHeaderLeft: {
            display: 'flex',
            alignItems: 'center',
            gap: theme.spacing(1.25),
        },
        filterIconBadge: {
            width: 30,
            height: 30,
            borderRadius: 9,
            background: `linear-gradient(135deg, ${primary} 0%, ${alpha(primary, 0.7)} 100%)`,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: `0 2px 8px ${alpha(primary, 0.4)}`,
            flexShrink: 0,
        },
        filterTitle: {
            fontSize: 13,
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
            letterSpacing: '-0.01em',
        },
        filterCountChip: {
            height: 18,
            borderRadius: 6,
            background: primary,
            color: '#fff',
            fontSize: 10,
            fontWeight: 800,
            display: 'flex',
            alignItems: 'center',
            padding: '0 7px',
        },
        filterChevron: {
            width: 26,
            height: 26,
            borderRadius: 8,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: isDark ? alpha('#fff', 0.07) : alpha(secondary, 0.07),
            transition: 'transform 0.25s ease',
        },
        filterChevronOpen: {
            transform: 'rotate(180deg)',
        },
        filterBody: {
            padding: theme.spacing(2.5),
            paddingTop: theme.spacing(2),
            borderTop: '1.5px solid',
            borderColor: isDark ? alpha('#fff', 0.08) : alpha(secondary, 0.1),
        },
        filterGrid: {
            display: 'grid',
            gap: theme.spacing(2),
            gridTemplateColumns: '1fr',
            [theme.breakpoints.up('sm')]: {
                gridTemplateColumns: '1fr 1fr',
            },
            [theme.breakpoints.up('md')]: {
                gridTemplateColumns: 'repeat(5, 1fr)',
            },
        },
        labelText: {
            fontSize: 10,
            fontWeight: 700,
            letterSpacing: '0.07em',
            textTransform: 'uppercase',
            color: theme.palette.text.secondary,
            marginBottom: 6,
            display: 'flex',
            alignItems: 'center',
            gap: 4,
            opacity: 0.7,
            minHeight: 14,
        },
        inputRoot: {
            '& .MuiOutlinedInput-root': {
                borderRadius: 5,
                backgroundColor: isDark ? alpha('#fff', 0.05) : theme.palette.background.paper,
                fontSize: 13,
                height: 40,
                fontWeight: 500,
                '& fieldset': {
                    borderColor: isDark ? alpha('#fff', 0.12) : alpha(secondary, 0.18),
                    borderWidth: 1.5,
                },
                '&:hover fieldset': {
                    borderColor: alpha(primary, 0.55),
                },
                '&.Mui-focused fieldset': {
                    borderColor: primary,
                    boxShadow: `0 0 0 3px ${alpha(primary, 0.15)}`,
                },
            },
        },
        searchButton: {
            height: 40,
            borderRadius: 10,
            fontWeight: 700,
            fontSize: 13,
            textTransform: 'none',
            boxShadow: `0 3px 10px ${alpha(primary, 0.4)}`,
        },
        clearButton: {
            height: 40,
            borderRadius: 10,
            fontWeight: 700,
            fontSize: 13,
            textTransform: 'none',
        },
        filterActionsRow: {
            marginTop: theme.spacing(1.5),
            display: 'flex',
            justifyContent: 'flex-end',
            gap: theme.spacing(1),
        },
        accordionRoot: {
            borderRadius: '14px !important',
            border: '1px solid',
            borderColor: isDark ? alpha('#fff', 0.09) : alpha(secondary, 0.12),
            overflow: 'hidden',
            boxShadow: 'none',
            '&:before': {
                display: 'none',
            },
            '&.Mui-expanded': {
                margin: 0,
            },
        },
        accordionSummary: {
            position: 'relative',
            paddingLeft: theme.spacing(3.5),
            minHeight: 56,
            background: isDark ? alpha(secondary, 0.35) : alpha(secondary, 0.035),
            '&::before': {
                content: '""',
                position: 'absolute',
                left: 0,
                top: 0,
                bottom: 0,
                width: 5,
                background: `linear-gradient(180deg, ${primary} 0%, ${alpha(primary, 0.6)} 100%)`,
            },
            '&.Mui-expanded': {
                minHeight: 56,
                borderBottom: '1px solid',
                borderColor: isDark ? alpha('#fff', 0.08) : alpha(secondary, 0.1),
            },
        },
        accordionSummaryContent: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: theme.spacing(1.5),
            flexWrap: 'wrap',
            width: '100%',
            paddingRight: theme.spacing(1),
        },
        customerIdentity: {
            display: 'flex',
            flexDirection: 'column',
            gap: 2,
            minWidth: 0,
        },
        customerName: {
            fontSize: 16,
            fontWeight: 800,
            letterSpacing: '0.01em',
            color: isDark ? '#fff' : secondary,
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
        },
        customerMeta: {
            fontSize: 12,
            fontWeight: 600,
            color: theme.palette.text.secondary,
            opacity: 0.75,
        },
        orderCountChip: {
            fontSize: 11,
            fontWeight: 800,
            height: 22,
            background: isDark ? alpha('#fff', 0.08) : alpha(secondary, 0.08),
            color: isDark ? '#fff' : secondary,
        },
        accordionDetails: {
            display: 'flex',
            flexDirection: 'column',
            gap: theme.spacing(1.5),
            padding: theme.spacing(1.5),
            background: isDark ? 'transparent' : alpha(secondary, 0.012),
        },
        orderCard: {
            borderRadius: 10,
            border: '1px solid',
            borderColor: isDark ? alpha('#fff', 0.1) : alpha(secondary, 0.4),
            background: theme.palette.background.paper,
            padding: theme.spacing(1.75, 2),
            contentVisibility: 'auto',
            containIntrinsicSize: '0 460px',
        },
        orderNumber: {
            fontSize: 18,
            fontWeight: 800,
            color: primary,
            letterSpacing: '-0.01em',
        },
        orderMetaLine: {
            fontSize: 12,
            color: theme.palette.text.secondary,
            marginTop: 1,
        },
        orderMetaStrong: {
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
        },
        topRightCol: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-end',
            gap: 6,
        },
        approveButton: {
            height: 35,
            fontSize: 14,
            fontWeight: 700,
            textTransform: 'none',
            borderRadius: 7,
            boxShadow: `0 3px 10px ${alpha(primary, 0.35)}`,
        },
        approveChip: {
            height: 26,
            fontSize: 11.5,
            fontWeight: 800,
        },
        payoutInput: {
            width: 140,
            '& .MuiOutlinedInput-root': {
                height: 35,
                fontSize: 12,
                borderRadius: 6,
                fontWeight: 700,
            },
            '& input': {
                padding: '2px 8px',
            },
        },
        infoBox: {
            borderRadius: 10,
            border: '1px solid',
            borderColor: isDark ? alpha('#fff', 0.09) : alpha(secondary, 0.11),
            background: isDark ? alpha('#fff', 0.02) : alpha(secondary, 0.02),
            padding: theme.spacing(1.25, 1.5),
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            gap: 4,
            flexGrow: 1,
        },
        infoSubBox: {
            borderRadius: 8,
            background: isDark ? alpha('#fff', 0.03) : alpha(secondary, 0.035),
            padding: theme.spacing(1, 1.25),
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            gap: 4,
        },
        boxTitle: {
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 13,
            fontWeight: 800,
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
            marginBottom: 6,
            paddingBottom: 6,
            borderBottom: '1px solid',
            borderColor: isDark ? alpha('#fff', 0.08) : alpha(secondary, 0.09),
        },
        boxTitle_shipper: {
            color: shipperColor,
        },
        boxTitle_receiver: {
            color: receiverColor,
        },
        boxTitle_waiting: {
            color: primary,
        },
        boxTitle_neutral: {
            color: secondary,
            opacity: isDark ? 0.9 : 0.85,
        },
        partyName: {
            fontSize: 13,
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
        },
        addressText: {
            fontSize: 12,
            color: theme.palette.text.secondary,
        },
        specialInstructions: {
            display: '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical',
            overflow: 'hidden',
            fontSize: 12,
            color: theme.palette.text.secondary,
            marginTop: 2,
        },
        timeCol: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-end',
            gap: 2
        },
        timeLabel: {
            display: 'flex',
            alignItems: 'center',
            gap: 4,
            fontSize: 12,
            fontWeight: 700,
            color: theme.palette.text.secondary,
            textTransform: 'uppercase',
            letterSpacing: '0.04em',
        },
        dateValue: {
            fontSize: 13,
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
            marginTop: 2,
        },
        timeRangeValue: {
            fontSize: 12,
            color: theme.palette.text.secondary,
        },
        kvRow: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'baseline',
            gap: 8,
            textAlign: 'center',
        },
        kvColumn: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'baseline',
            gap: 2,
        },
        kvLabel: {
            fontSize: 12,
            color: theme.palette.text.secondary,
        },
        kvValue: {
            fontSize: 13,
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
        },
        kvValueEmphasis: {
            fontSize: 13.5,
            fontWeight: 800,
            color: isDark ? '#fff' : secondary,
        },
        kvTotal: {
            fontSize: 20,
            color: theme.palette.text.secondary,
            fontWeight: 700,
        },
        kvTotalValue: {
            fontSize: 21,
            fontWeight: 700,
            color: isDark ? '#fff' : primary,
        },
        freightLineRow: {
            display: 'grid',
            gridTemplateColumns: '22px 48px 1fr auto',
            gap: '0 8px',
            alignItems: 'baseline',
            marginBottom: 3,
        },
        freightPieces: {
            fontSize: 12,
            fontWeight: 800,
            color: primary,
        },
        freightType: {
            fontSize: 12,
            color: isDark ? '#fff' : secondary,
            opacity: 0.85,
        },
        freightDims: {
            fontSize: 12,
            color: theme.palette.text.secondary,
        },
        freightDescription: {
            fontSize: 12,
            fontWeight: 700,
            color: isDark ? '#fff' : secondary,
        },
        chargesTitleRow: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        editButton: {
            width: 28,
            height: 28,
            borderRadius: 8,
            marginTop: -6,
            background: isDark ? alpha('#fff', 0.08) : alpha(primary, 0.08),
            border: '1px solid',
            borderColor: alpha(primary, 0.3),
            '&:hover': {
                background: alpha(primary, 0.18),
            },
        },
        sectionDivider: {
            borderStyle: 'dashed',
            borderColor: isDark ? alpha('#fff', 0.15) : alpha(secondary, 0.18),
            margin: '2px 0',
        },
        serviceChip: {
            height: 26,
            fontSize: 15,
            fontWeight: 800,
            letterSpacing: '0.03em',
            borderRadius: 6,
            alignSelf: 'flex-start',
        },
        serviceChipDirect: {
            background: alpha('#2980b9', 0.14),
            color: '#2980b9',
        },
        serviceChipRush: {
            background: alpha('#e67e22', 0.16),
            color: '#e67e22',
        },
        serviceChipRegular: {
            background: alpha(secondary, 0.1),
            color: secondary,
        },
        notesText: {
            fontSize: 12,
            color: theme.palette.text.secondary,
        },
        emptyState: {
            padding: theme.spacing(8),
            textAlign: 'center',
            border: '1px dashed',
            borderColor: isDark ? alpha('#fff', 0.15) : alpha(secondary, 0.2),
            borderRadius: 14,
            color: theme.palette.text.secondary,
        },
        listWrap: {
            display: 'flex',
            flexDirection: 'column',
            gap: theme.spacing(2),
            transition: 'opacity 0.15s ease',
        },
        listWrapFetching: {
            opacity: 0.5,
        },
        paginationBar: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            flexWrap: 'wrap',
            gap: theme.spacing(1.5),
            padding: theme.spacing(2, 0.5, 0.5),
        },
        paginationInfo: {
            fontSize: 12.5,
            color: theme.palette.text.secondary,
            display: 'flex',
            alignItems: 'center',
            gap: 8,
        },
        rowsPerPageSelect: {
            height: 32,
            fontSize: 12.5,
            fontWeight: 600,
            borderRadius: 8,
        },
        muiPaginationRoot: {
            '& .MuiPaginationItem-root': {
                fontWeight: 700,
                fontSize: 13,
                borderRadius: 9,
            },
            '& .Mui-selected': {
                background: `${primary} !important`,
                color: '#fff',
                boxShadow: `0 3px 10px ${alpha(primary, 0.4)}`,
            },
        },
        driverNotes: {
            margin: 0,
            paddingInline: theme.spacing(3)
        }
    };
});