import moment from "moment";

export const defaultOrderValue = {
  username: '',
  order_number: '',
  create_date: new Date(),
  terminal: '',
  quote: false,
  is_crossdock: false,
  order_entity: 'Order Entry',
  order_status: 'Pending',
  internal_note: '',

  customer_id: '',
  // customer: '',

  reference_numbers: [],
  caller: '',

  shipper_id: '',
  shipper_email: '',
  shipper_contact_name: '',
  shipper_phone_number: '',
  shipper_address: '',
  shipper_suite: '',
  shipper_city: '',
  shipper_province: '',
  shipper_postal_code: '',
  shipper_special_instructions: '',
  shipper_no_waiting_time: false,

  is_extra_stop: false,
  extra_stop_id: '',
  extra_stop_email: '',
  extra_stop_contact_name: '',
  extra_stop_phone_number: '',
  extra_stop_address: '',
  extra_stop_suite: '',
  extra_stop_city: '',
  extra_stop_province: '',
  extra_stop_postal_code: '',
  extra_stop_special_instructions: '',

  receiver_id: '',
  receiver_email: '',
  receiver_contact_name: '',
  receiver_phone_number: '',
  receiver_address: '',
  receiver_suite: '',
  receiver_city: '',
  receiver_province: '',
  receiver_postal_code: '',
  receiver_special_instructions: '',
  receiver_no_waiting_time: false,

  pickup_date: new Date(),
  pickup_time_from: '07:00',
  pickup_time_to: '07:00',
  pickup_driver_assigned: '',
  pickup_terminal: '',
  pickup_appointment: false,
  pickup_appointment_numbers: [],

  is_pickup: false,
  is_delivery: false,
  is_same_carrier: false,

  interliner_id: '',
  interliner_special_instructions: '',
  interliner_charge_amount: '',
  interliner_invoice: '',

  interliner_pickup_id: '',
  interliner_pickup_special_instructions: '',
  interliner_pickup_charge_amount: '',
  interliner_pickup_invoice: '',

  interliner_delivery_id: '',
  interliner_delivery_special_instructions: '',
  interliner_delivery_charge_amount: '',
  interliner_delivery_invoice: '',

  delivery_date: new Date(),
  delivery_time_from: '12:00',
  delivery_time_to: '12:00',
  delivery_driver_assigned: '',
  delivery_terminal: '',
  delivery_appointment: false,
  delivery_appointment_numbers: [],

  service_type: 'Regular',
  freights: [
    {
      type: 'Skid',
      description: 'FAK',
      pieces: 1,
      weight: '',
      unit: 'lbs',
      length: '',
      width: '',
      height: '',
      dim_unit: 'in',
      not_stack: false,
      volume_weight: 0,
      is_converted: false
    }
  ],

  is_manual_skid: false,
  total_pieces: 0,
  total_pieces_skid: 0,
  total_actual_weight: 0,
  total_volume_weight: 0,
  total_chargeable_weight: 0,
  total_weight_in_kg: 0,

  no_charges: false,
  manual_charges: false,
  manual_fuel_surcharges: false,
  freight_rate: 0,
  freight_fuel_surcharge: 0,

  direct_km: 0,
  customer_vehicle_types: [],
  customer_accessorials: [],
  additional_service_charges: [],
  sub_total: 0,
  provincial_tax: 0,
  federal_tax: 0,
  grand_tax: 0,

  pickup_in: null,
  pickup_out: null,
  pickup_at: null,
  delivery_in: null,
  delivery_out: null,
  delivery_at: null,
  pickup_signee: '',
  delivery_signee: '',
  billing_invoice_date: new Date(),
  billing_invoice: '',
  billing_invoiced: false,
  total_pickup: 0,
  total_delivery: 0,
  total_time: 0
}
