import moment from "moment";

export const defaultOrderValue = {
  username: '',
  order_number: '',
  create_date: new Date(),
  terminal: '',
  quote: false,
  is_crossdock: false,
  order_entity: 'Order Entry',
  order_status: 'Pending',
  internal_note: '',
  customer_id: '',
  reference_numbers: [],
  caller: '',
  shipper_id: '',
  shipper_email: '',
  shipper_contact_name: '',
  shipper_phone_number: '',
  shipper_address: '',
  shipper_suite: '',
  shipper_city: '',
  shipper_province: '',
  shipper_postal_code: '',
  shipper_special_instructions: '',
  is_extra_stop: false,
  extra_stop_id: '',
  extra_stop_email: '',
  extra_stop_contact_name: '',
  extra_stop_phone_number: '',
  extra_stop_address: '',
  extra_stop_suite: '',
  extra_stop_city: '',
  extra_stop_province: '',
  extra_stop_postal_code: '',
  extra_stop_special_instructions: '',
  receiver_id: '',
  receiver_email: '',
  receiver_contact_name: '',
  receiver_phone_number: '',
  receiver_address: '',
  receiver_suite: '',
  receiver_city: '',
  receiver_province: '',
  receiver_postal_code: '',
  receiver_special_instructions: '',
  pickup_date: new Date(),
  pickup_time_from: '07:00 PM',
  pickup_time_to: '07:00 PM',
  pickup_driver_assigned: '',
  pickup_terminal: '',
  pickup_appointment: false,
  pickup_appointment_numbers: [],
  interline_carrier: {
    isPickup: false,
    isDelivery: false,
    isSameCarrier: false,
    sameCarrier: {
      interline: '',
      email: '',
      contact_name: '',
      phone_number: '',
      address: '',
      suite: '',
      city: '',
      province: '',
      postal_code: '',
      special_intructions: '',
      charge_amount: '',
      invoice: ''
    },
    pickup: {
      interline: '',
      email: '',
      contact_name: '',
      phone_number: '',
      address: '',
      suite: '',
      city: '',
      province: '',
      postal_code: '',
      special_intructions: '',
      charge_amount: '',
      invoice: ''
    },
    delivery: {
      interline: '',
      email: '',
      contact_name: '',
      phone_number: '',
      address: '',
      suite: '',
      city: '',
      province: '',
      postal_code: '',
      special_intructions: '',
      charge_amount: '',
      invoice: ''
    }
  },
  delivery_date: new Date(),
  delivery_time_from: '12:00 PM',
  delivery_time_to: '12:00 PM',
  delivery_driver_assigned: '',
  delivery_terminal: '',
  delivery_appointment: false,
  delivery_appointment_numbers: [],
  freight_details: {
    service_type: 'Regular',
    freights: [
      {
        type: 'Skid',
        description: 'FAK',
        pieces: 1,
        weight: '',
        unit: 'lbs',
        length: '',
        width: '',
        height: '',
        dim_unit: 'IN',
        not_stack: false,
        is_converted: false
      }
    ]
  },
  freight_charges: {
    no_charges: false,
    manual_charges: false,
    manual_fuel_surcharges: false,
    freight_rate: '',
    freight_fuel_surcharge: '',
    additional_service_charges: []
  }
}
